networks:
  application:
    internal: false

services:
  minio:
    image: quay.io/minio/minio:latest
    container_name: minio
    restart: unless-stopped
    command: server /data --console-address ":9001"
    networks:
      - application
    ports:
          # S3 API port (9000:9000)
          - name: s3-api
            protocol: tcp
            published: 9000
            target: 9000
          # MinIO Console/Web UI port (9001:9001)
          - name: minio-web
            protocol: tcp
            published: 9001
            target: 9001
    environment:
      MINIO_ROOT_USER: administrator
      MINIO_ROOT_PASSWORD: administrator
    volumes:
      - minio_data:/data

volumes:
  minio_data:
