# Copyright (C) 2025 ZedCloud Org.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.

workers: 100
interval: 24h
drive:
  account-file: /path/to/redacted/svc-account.json
  subject: "[REDACTED_ADMIN_EMAIL]"
  current-account: true
  shared-drive: true
  other-users: true
s3:
  bucket: bucket-name
  client-id: "[REDACTED_CLIENT_ID]"
  client-secret: "[REDACTED_CLIENT_SECRET]"
  endpoint: "[REDACTED_PRIVATE_ENDPOINT]"
  cache-expiry: 1m
